app:
  name: "sc_police_api"
  node: "dev"
  port: ":8088"

log:
  level: "info"
  filename: "log/sc_police_api.log"
  max_size: 100 # 文件大小 MB
  max_age: 30 # 保留天数
  max_backups: 10 # 最大备份数

database:
  host: "192.168.31.85"
  port: 5432
  user: "sc_po_db"
  password: "......."
  dbname: "sc_po_db"

# 用不到redis
# redis:
#   host: "127.0.0.1"
#   port: 6379
#   db: 0
